export const FETCH_LIVE_LIST_SUCCESS = 'FETCH_LIVE_LIST_SUCCESS'
export const FETCH_ROOM_LIST_SUCCESS = 'FETCH_ROOM_LIST_SUCCESS'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_CATEGORY_LIST_SUCCESS'
